### ISSUE TITLE
Microsoft.AspNetCore.Components.RenderTree not found

### ISSUE THREAD

**Issue by JokerWhiteHeart** [SteveSandersonMS/BlazorUnitTestingPrototype#1]
Hi @SteveSandersonMS ,

I am facing 

> Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	CS0234	The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.RenderTree' (are you missing an assembly reference?)	SampleApp	D:\BlazorTesting\protoType\BlazorUnitTestingPrototype\SampleApp\Pages\Index.razor	1		Active
 

error when i am compiled your src. I analyzed you have you used preview 9 . Is i am update my sdk to preview 9 or else i am missing any thing myside?

please help to resolve this.

**Comment by stsrki** [comment]
@JokerWhiteHeart The same error is happening to me so I guess it must be related to missing latest sdk.

**Comment by egil** [comment]
Steve said on Twitter that it is built using preview 9 (that should be out on 4. September).

**Comment by SteveSandersonMS** [comment]
Yes, please upgrade to preview 9 which is now released.
